### ISSUE TITLE
[TiempoReal] Inconsistencias detectando si el reloj está en mano

### ISSUE THREAD

**Issue by AlexTMjugador** [AlexTMjugador/mc-khron-plugins#1]
El código actual para detectar si un jugador pasa a tener el reloj en su mano principal o secundaria no contempla todos los casos de gestión de inventario relevantes, lo que hace necesario provocar otro evento sí gestionado para que la hora se muestre o no apropiadamente. La experiencia del usuario sería más consistente de arreglarse esto.

**Comment by MiguelDreamer** [comment]
Este problema se ha solucionado en la versión 2.0 de TiempoReal
