### ISSUE TITLE
Activar/Desactivar la hora real en diferentes mundos

### ISSUE THREAD

**Issue by MiguelDreamer** [AlexTMjugador/mc-khron-plugins#2]
En este momento, el plugin de TiempoReal adapta la hora en todos los mapas/dimensiones. Esto no importa en el Nether y en el End, pero cuando se añadan otros mundos (por ejemplo, uno de supervivencia) se tendría que añadir configuraciones en el plugin, como poder activar o desactivar la hora real en los mundos que quieras.

Y como sugerencia, ya que los relojes no funcionan en el Nether y en el End, ¿qué tal si en vez de mostrar ''El reloj marca las XX:XX'' pone una frase acorde con la dimensión o con carácteres aleatorios?

**Comment by AlexTMjugador** [comment]
Me parece bastante acertada la segunda sugerencia, pues en dimensiones diferentes al mundo normal no existe el concepto de hora, día y noche.

**Comment by AlexTMjugador** [comment]
[Implementado](https://github.com/AlexTMjugador/mc-khron-plugins/commit/a3089105bf1c713f410fa0e4f5aa635ddabb0096).
